logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
logging.level.org.springframework.web: TRACE
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: '3030'
  servlet:
    context-path: /management/v1
  error:
    include-binding-errors: always
    include-message: always
management:
  security:
    enabled: false
management.endpoints.web.exposure.include: "health,info"
management.endpoint.health.show-details: always
management.endpoint.health.probes.enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/happy_learn?stringtype=unspecified"
    username: postgres
    password: iloveyou

person-manager:
  http:
    baseUrl: http://localhost:3030



